modLoader="javafml"
loaderVersion="[4,)"
license="LGPL-3.0-only"

[[mods]]
modId="voxy"
version="${version}-${commit}"
displayName="Voxy"
authors="MCRcortex, NeoForge port by SlaVKs/Codex"
description='''Voxel-based distant terrain renderer for Minecraft.'''

[[mixins]]
config="common.voxy.mixins.json"

[[mixins]]
config="client.voxy.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[modproperties.voxy]
"sodium:config_api_user"="me.cortex.voxy.client.config.VoxyConfigMenu"

[[dependencies.voxy]]
modId="neoforge"
type="required"
versionRange="[21.1.224,)"
ordering="NONE"
side="BOTH"

[[dependencies.voxy]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"

[[dependencies.voxy]]
modId="sodium"
type="required"
versionRange="[0.8.12,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.voxy]]
modId="iris"
type="optional"
versionRange="[1.8.0,)"
ordering="AFTER"
side="CLIENT"
