package me.cortex.voxy.client.sodium.provider;

public enum VoxyTerrainFailureReason {
    NONE,
    MISSING_EXACT_CHILD,
    VALID_PARENT_FALLBACK,
    INVALID_PALETTE_ID,
    UNRESOLVED_BLOCK_STATE,
    MISSING_MODEL_FALLBACK,
    MISSING_BIOME_TINT,
    INVALID_LIGHT,
    UNTRUSTED_SOURCE,
    SECTION_OUT_OF_BOUNDS,
    PARENT_CHILD_OWNERSHIP_CONFLICT,
    RENDER_PASS_UNSUPPORTED,
    STALE_UPLOAD
}
